version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-streaming
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=streaming
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
